# Generated by Django 2.2.13 on 2021-12-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='pin',
        ),
    ]
