# Generated by Django 2.2.13 on 2021-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200303_2140'),
        ('noticeboard', '0002_remove_noticeboard_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='notice_contact', to='authentication.UserProfile'),
        ),
    ]
